### PR TITLE
fix: don't require `stream` package in codebase

### LINKED ISSUE #516: When upgrading from `4.3.0` to `4.4.0`, using `esbuild --bundle` to build will report an error `Could not resolve "stream"`
This is an example file `test.js`:

```js
require('readable-stream');
```

Run the following commands (esbuild@0.17.12):

```bash
esbuild --bundle test.js
```

It outputs:

```
✘ [ERROR] Could not resolve "stream"

    node_modules/.pnpm/readable-stream@4.4.0/node_modules/readable-stream/lib/stream/promises.js:7:8:
      7 │ require('stream')
        ╵         ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

1 error
```

If I use version `4.3.0`, it will output correctly.

### PR DESCRIPTION
**Pull request by jeswr**
Closes #516.

Supercedes #517 and #519.

This replaces `require('stream')` with `require('../../lib/stream.js')` in the build script so that the `stream` module is never imported.

Since #517 I've moved the regression test to a new folder in the root since the other test fixtures are being copied from the nodejs codebase; wheras the one I add is specific to `readable-stream`.

### CODE REVIEW

File: readable-stream-test/runner-prepare.mjs [hunk 1]
```diff
@@ -0,0 +1,77 @@
+import { exec } from 'child_process'
```
Comment (mcollina) [inline readable-stream-test/runner-prepare.mjs:1]: why is this needed?

Comment (jeswr) [reply readable-stream-test/runner-prepare.mjs:1]: See line 27 (note this is a copy /paste of a subset of the code in the nodejs fixtures)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jeswr** [comment]
Bump @vweevers @benjamingr

**Comment by jeswr** [comment]
@mcollina it doesn't look like the others have time to review so can this be released?

**Comment by rubensworks** [comment]
Would it be possible to merge this package? Many of our downstream users are running into issues because of this

Happy to help where possible!

**Review by mcollina — APPROVED** [review]
lgtm
